# Generated by Django 4.1.4 on 2022-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
