# Generated by Django 4.1.4 on 2022-12-13 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_followers_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
    ]
